# -*- coding: utf-8 -*-
"""BucketSort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HXTdhy6YmRGWf1L4mGmgr2yMi-1ec9vr
"""

nums = [0.22, 0.99, 0.77, 0.22, 0.42, 0.53] 
def bucket_sort(nums):
  bucket = []
  for i in range(0,len(nums)):
    bucket.append([])

  for i in range(0, len(nums)):
    bucketLocation = int(nums[i] * len(nums) )
    bucket[bucketLocation].append(nums[i])

  for j in range(0, len(nums)):
    bucket[j].sort()
    
  index = 0
  for i in range(0,len(nums)):
    for j in range(0, len(bucket[i])):
      nums[index] = bucket[i][j]
      index = index + 1
  print("Sorted Elements : {0}".format(nums))

bucket_sort(nums)

